apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-aggregator-deployment
  labels:
    app: state-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: state-aggregator
  template:
    metadata:
      labels:
        app: state-aggregator
    spec:
      containers:
        - name: state-aggregator
          image: varcavia/state-aggregator:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: REDIS_ADDR
              value: "redis-service:6379"
          volumeMounts:
            - name: dna-volume
              mountPath: /app/dna # I file saranno disponibili qui
              readOnly: true
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:50051"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      volumes:
        - name: dna-volume
          configMap:
            name: varcavia-dna
