apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VarcaviaSignedImages
metadata:
  name: require-signed-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    image: "gcr.io/varcavia-project/*"
    issuer: "https://accounts.google.com"
    subject: "identity-of-your-ci-cd-service-account"
