apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-aggregator
  namespace: varcavia-services
  labels:
    app: state-aggregator
    workload-priority: critical
spec:
  replicas: 2
  selector:
    matchLabels:
      app: state-aggregator
  template:
    metadata:
      labels:
        app: state-aggregator
        workload-priority: critical
    spec:
      containers:
        - name: state-aggregator
          image: ghcr.io/varcavia-inc/state-aggregator:latest
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - /bin/grpc-health-probe
                - -addr=:50051
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - /bin/grpc-health-probe
                - -addr=:50051
            initialDelaySeconds: 5
            periodSeconds: 10
