apiVersion: v1
kind: Service
metadata:
  name: state-aggregator
  namespace: varcavia-services
  labels:
    app: state-aggregator
spec:
  type: ClusterIP
  selector:
    app: state-aggregator
  ports:
    - name: grpc
      port: 80
      targetPort: 50051
