name: 1. Manager Bot Orchestration

on:
  # Trigger principale per avviare nuove missioni
  push:
    branches: [ main ]
    paths:
      - 'src/business_plan.yaml'
  
  # Trigger per l'attivazione manuale
  workflow_dispatch:

  # --- POTENZIAMENTO CHIAVE ---
  # Trigger reattivo: si attiva ISTANTANEAMENTE quando il workflow di validazione finisce.
  workflow_run:
    workflows: ["4. PR Validation"]
    types:
      - completed

jobs:
  run_manager_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write 
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with: { token: '${{ secrets.BOT_GITHUB_TOKEN }}' }
      
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/826570341026/locations/global/workloadIdentityPools/varcavia-github-pool/providers/varcavia-github-provider'
          service_account: 'vertex-client@varcavia-office-bc6xvv.iam.gserviceaccount.com'

      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }

      - name: Install Dependencies & Run
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GCP_PROJECT: 'varcavia-office-bc6xvv'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install -r requirements.txt
          gh auth setup-git
          python src/bots/manager_bot.py