name: 2. Operator Bot Task Execution

on:
  workflow_dispatch:
    inputs:
      branch_name: { required: true }
      task_description: { required: true }
      commit_message: { required: true }

jobs:
  execute_task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with: { token: '${{ secrets.BOT_GITHUB_TOKEN }}' }

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/826570341026/locations/global/workloadIdentityPools/varcavia-github-pool/providers/varcavia-github-provider'
          service_account: 'vertex-client@varcavia-office-bc6xvv.iam.gserviceaccount.com'

      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }

      - name: Install Dependencies & Run
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}
          TASK_DESCRIPTION: ${{ github.event.inputs.task_description }}
          COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GCP_PROJECT: 'varcavia-office-bc6xvv'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install -r requirements.txt
          gh auth setup-git
          python src/bots/operator_bot.py