name: Docker Build • Test • Push

on:
  push:
    branches: [ "main" ]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # ---------- calcola IMAGE_NAME lowercase ----------
      - name: Compute IMAGE_NAME
        run: |
          echo "IMAGE_NAME=ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install buf & protoc plugins
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.30.0/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Generate protobuf
        run: |
          cd schemas
          buf mod update
          buf generate
          cd ..

      - name: Unit tests
        run: |
          go vet ./...
          go test ./...

      # ---------- Build image (local) ----------
      - name: Build image for integration test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/state_aggregator/Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # ---------- Install grpcurl ----------
      - name: Install grpcurl
        run: |
          GRPCURL_VERSION=1.9.3
          curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz" \
          | tar -xz -C /usr/local/bin grpcurl

      # ---------- Integration test ----------
      - name: Integration test via compose
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker compose -f test/integration/docker-compose.yaml up -d
          test/integration/smoke.sh
          docker compose -f test/integration/docker-compose.yaml down -t 0

      # ---------- Login and push on main branch ----------
      - name: Login to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/state_aggregator/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # ---------- Sign container image ----------
      - name: Install Cosign
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign image with Cosign
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes ${{ env.IMAGE_NAME }}:${{ github.sha }}
