name: Go CI – Build, Lint & Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - 'schemas/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/ci-go.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - 'schemas/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/ci-go.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # ---------- buf + protoc plugins ----------
      - name: Install buf & protoc plugins
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.30.0/buf-Linux-x86_64 \
            -o /usr/local/bin/buf && chmod +x /usr/local/bin/buf
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Generate protobuf
        run: |
          cd schemas
          buf mod update                   # risolve warning deps
          buf generate
          cd ..

      - name: Lint & Vet
        run: make lint

      - name: Unit tests
        run: go test ./...
