name: Go CI - Build, Lint & Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - 'schemas/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/ci-go.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/**'
      - 'schemas/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/ci-go.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # ---------- QUI il fix: action corretta ----------
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.30.0

      - name: Install Go dependencies
        run: go mod download

      - name: Generate Protobuf code
        run: make proto

      - name: Lint & Vet
        run: make lint

      - name: Run tests (se presenti)
        run: go test ./...

      - name: Build Docker image (local only)
        run: make build
