name: ci-lint-and-test
on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
  push:
    branches: [main]
    paths:
      - '**/*.go'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59.0

      - name: Vet & test (stable pkgs)
        run: |
          pkgs=$(go list ./... | grep -v '/services/architect_service' | grep -v '/services/state_aggregator')
          go vet $pkgs
          go test -v $pkgs
