name: ci-security-scan
on:
  pull_request:
    paths:
      - '**/*.go'
      - '**/*.proto'
      - 'services/**'
      - 'Dockerfile'
      - 'Makefile'
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/*.proto'
      - 'services/**'
      - 'Dockerfile'
      - 'Makefile'

jobs:
  ci-security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Trivy Filesystem Scan (CRITICAL/HIGH)
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: '1'
