name: Security Scan
on:
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run gosec (code linter)
        uses: securego/gosec@v2.18.2
        with:
          args: ./...

      - name: Run Trivy (SBOM & vuln)
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: '1'
          format: table
