name: Debug WIF Configuration

on:
  workflow_dispatch: # Permette di avviarlo a mano

jobs:
  debug_values:
    runs-on: ubuntu-latest
    steps:
      - name: Print WIF Values for Verification
        run: |
          echo "--- VERIFICA VALORI SECRET ---"
          echo "GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}"
          echo "GCP_WIF_POOL: ${{ secrets.GCP_WIF_POOL }}"
          echo "GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}"
          echo "GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}"
          echo "---------------------------------"
          echo ""
          echo "--- STRINGA 'AUDIENCE' COSTRUITA ---"
          echo "//iam.googleapis.com/projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL }}/providers/${{ secrets.GCP_WIF_PROVIDER }}"
          echo "------------------------------------"