name: Debug Runner Availability

on:
  workflow_dispatch: # Permette di avviarlo a mano

jobs:
  test_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World! Se vedi questo messaggio, il Runner funziona."