name: AutoDevSystem Git Operations

on:
  push:
    paths:
      - '.autodev-trigger'
    branches:
      - main
  workflow_dispatch:

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} 
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Set up Git User
        run: |
          git config user.name "AutoDevSystem Bot"
          git config user.email "auto-dev-system@varcavia.com"

      - name: Read Trigger File and Prepare Git Operations
        id: read_trigger
        run: |
          # ... (contenuto del passo invariato) ...
          if [ ! -f ".autodev-trigger" ]; then
            echo "::error::Trigger file .autodev-trigger not found. Exiting."
            exit 1
          fi
          COMMIT_MESSAGE=$(grep "commit_message" .autodev-trigger | cut -d ':' -f 2- | sed 's/^ *//')
          TIMESTAMP=$(grep "timestamp" .autodev-trigger | cut -d ':' -f 2- | sed 's/^ *//')
          if [ -z "$COMMIT_MESSAGE" ]; then
            COMMIT_MESSAGE="AutoDevSystem: Unspecified task completion"
          fi
          NEW_BRANCH_NAME="autodev-task-${TIMESTAMP}"
          echo "Commit message: $COMMIT_MESSAGE"
          echo "New branch name: $NEW_BRANCH_NAME"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_OUTPUT
          rm .autodev-trigger

      - name: Create New Branch, Commit, and Push Changes
        run: |
          git checkout -b ${{ steps.read_trigger.outputs.NEW_BRANCH_NAME }}
          git add .
          git commit -m "${{ steps.read_trigger.outputs.COMMIT_MESSAGE }}"
          git push https://VARCAVIA-Git:${{ secrets.BOT_GITHUB_TOKEN }}@github.com/VARCAVIA-Inc/auto-dev-system.git ${{ steps.read_trigger.outputs.NEW_BRANCH_NAME }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh pr create --title "${{ steps.read_trigger.outputs.COMMIT_MESSAGE }}" \
                       --body "Automatically generated Pull Request by AutoDevSystem for task: ${{ steps.read_trigger.outputs.COMMIT_MESSAGE }}" \
                       --head ${{ steps.read_trigger.outputs.NEW_BRANCH_NAME }} \
                       --base main

  # --- NUOVO JOB DI NOTIFICA ---
  send_status_notification:
    runs-on: ubuntu-latest
    if: always()
    needs: [create_branch_and_pr]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install email dependencies
        run: pip install secure-smtplib

      - name: Send workflow status email
        env:
          JOB_STATUS: ${{ needs.create_branch_and_pr.result }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          PYTHONPATH: ${{ github.workspace }}
        run: python src/utils/report_generator.py
