# .github/workflows/main.yml
name: Manager Bot Orchestration

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'development_plan.md'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_manager_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write 
    outputs:
      summary: ${{ steps.summary.outputs.summary_text }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # MODIFICA: Usiamo requirements.txt per installare le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Manager Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GITHUB_USER: "VARCAVIA-Git"
          GITHUB_REPOSITORY: ${{ github.repository }}
          PYTHONPATH: ${{ github.workspace }}
        run: python src/manager_bot.py

      - name: Set run summary output
        id: summary
        if: always()
        run: |
          if [[ -f run_summary.txt ]]; then
            echo "summary_text=$(cat run_summary.txt)" >> $GITHUB_OUTPUT
          else
            echo "summary_text=Nessuna azione specifica eseguita." >> $GITHUB_OUTPUT
          fi
          
  send_status_notification:
    runs-on: ubuntu-latest
    if: always()
    needs: [run_manager_bot]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          # Aggiungiamo il caching anche qui
          cache: 'pip'
      - name: Install dependencies
        # E usiamo requirements.txt anche qui
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send workflow status email
        env:
          JOB_STATUS: ${{ needs.run_manager_bot.result }}
          RUN_SUMMARY: ${{ needs.run_manager_bot.outputs.summary }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          PYTHONPATH: ${{ github.workspace }}
        run: python src/utils/report_generator.py