name: Manager Bot Orchestration

on:
  push:
    branches:
      - main
    paths-ignore: # Ignora i push del file di trigger per evitare loop infiniti
      - '.autodev-trigger'
  workflow_dispatch: # Permette l'esecuzione manuale
  schedule:
    - cron: '0 0 * * *' # Ogni giorno a mezzanotte UTC
    permissions:
  contents: write
  pull-requests: write

jobs:
  run_manager_bot:
    runs-on: ubuntu-latest
    permissions: # Permessi espliciti per questo job
      contents: write # Permette al GITHUB_TOKEN di scrivere nel repository
      pull-requests: write # Permette di creare e gestire Pull Request
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Non specificare 'token:' qui, userà il GITHUB_TOKEN implicito con i permessi definiti sopra.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          pip install PyGithub
          pip install secure-smtplib
          pip install openai 
          pip install GitPython

      - name: Run Manager Bot
        env:
          # Passiamo tutti i secret al bot.
          # GITHUB_TOKEN qui è il tuo PAT esplicito (secrets.BOT_GITHUB_TOKEN).
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python src/manager_bot.py
