name: Manager Bot Orchestration

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette l'esecuzione manuale
  schedule:
    - cron: '0 0 * * *' # Ogni giorno a mezzanotte UTC

jobs:
  run_manager_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          pip install PyGithub
          pip install secure-smtplib
          pip install openai 
          pip install GitPython

      - name: Run Manager Bot
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # <--- AGGIUNGI QUESTA RIGA
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python src/manager_bot.py