name: Operator Bot Task Execution

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Il nome del nuovo branch per questo task'
        required: true
      task_description:
        description: 'La descrizione del singolo task da eseguire'
        required: true
      commit_message:
        description: 'Il messaggio di commit per questo task'
        required: true

jobs:
  execute_task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-gemini-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-gemini-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython google-generativeai

      - name: Run Operator Bot
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}
          TASK_DESCRIPTION: ${{ github.event.inputs.task_description }}
          COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GITHUB_USER: "VARCAVIA-Git"
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python src/operator_bot.py